models:
  - model: "cardiffnlp"
    model_path: "./weights/cardiffnlp_opt/model.onnx" # "cardiffnlp/twitter-xlm-roberta-base-sentiment"
    tokenizer: "./weights/cardiffnlp_opt"
  - model: "ivanlau"
    model_path: "./weights/ivanlau_opt/model.onnx" # "ivanlau/language-detection-fine-tuned-on-xlm-roberta-base"
    tokenizer: "./weights/ivanlau_opt"
  - model: "svalabs"
    model_path: "./weights/svalabs_opt/model.onnx" # "svalabs/twitter-xlm-roberta-crypto-spam"
    tokenizer: "./weights/svalabs_opt"
  - model: "EIStakovskii"
    model_path: "./weights/EIStakovskii_opt/model.onnx" # "EIStakovskii/xlm_roberta_base_multilingual_toxicity_classifier_plus"
    tokenizer: "./weights/EIStakovskii_opt"
  - model: "jy46604790"
    model_path: "./weights/jy46604790_opt/model.onnx" # "jy46604790/Fake-News-Bert-Detect"
    tokenizer: "./weights/jy46604790_opt"

port: 8080
workers: 1

timeout: 0.01

